---
.gitignore:
  paths:
    - .rerun.json
    - .librarian
    - .kitchen
    - .tmp
    - .bundle
    - bolt.log
    - Puppetfile.lock
    - modules
.gitlab-ci.yml:
  # we don't use GitLab
  unmanaged: true
.travis.yml:
  # removed Puppet 5 checks here
  remove_includes:
    - env: PUPPET_GEM_VERSION="~> 5.0" CHECK=parallel_spec
      rvm: 2.4.5
      stage: spec
appveyor.yml:
  # we don't use Appveyor
  unmanaged: true
Gemfile:
  required:
    ':development':
      - gem: 'rake'
      - gem: 'bolt'
        version: '>= 1.48.0'
      - gem: 'puppet-lint-absolute_template_path'
        version: '>= 1.0.1'
      - gem: 'puppet-lint-alias-check'
        version: '>= 0.1.1'
      - gem: 'puppet-lint-classes_and_types_beginning_with_digits-check'
        version: '>= 0.1.2'
      - gem: 'puppet-lint-concatenated_template_files-check'
        version: '>= 0.1.1'
      - gem: 'puppet-lint-file_ensure-check'
        version: '>= 0.3.1'
      - gem: 'puppet-lint-file_source_rights-check'
        version: '>= 0.1.1'
      - gem: 'puppet-lint-leading_zero-check'
        version: '>= 0.1.1'
      - gem: 'puppet-lint-resource_reference_syntax'
        version: '>= 1.0.10'
      - gem: 'puppet-lint-trailing_comma-check'
        version: '>= 0.3.2'
      - gem: 'puppet-lint-unquoted_string-check'
        version: '>= 0.3.0'
      - gem: 'puppet-lint-version_comparison-check'
        version: '>= 0.2.1'
      - gem: 'puppetlabs_spec_helper'
      - gem: 'r10k'
        version: '>= 3.0.0'
      - gem: 'rspec-puppet-facts'
      # cri is needed by r10k, but due to a bug in the cri gem v2.15.7 it breaks r10k
      # see: https://github.com/puppetlabs/r10k/issues/930
      - gem: 'cri'
        version: '2.15.6'
      - gem: 'yaml-lint'
        version: '>= 0.0.10'
spec/spec_helper.rb:
  mock_with: ':rspec'
  spec_overrides:
    - '# setup for Bolt spec tests'
    - "require 'bolt_spec/plans'"
    - 'BoltSpec::Plans.init'
    - 'include BoltSpec::Plans'
    - ''
    - '# setup the proper modulepath for Bolt'
    - 'base_dir = File.dirname(File.expand_path(__FILE__))'
    - 'RSpec.configure do |c|'
    - '  # should we just use rspec_puppet'
    - '  c.add_setting :module_path'
    - "  c.module_path = File.join(base_dir, 'fixtures', 'modules')"
    - 'end'

